// {
//     id:,
//     image:"images/.jpg",
//     name:"",
//     category:"",
//     price:"₹",
//     description:"", 
// },

const Menu = [
    {
        id:1,
        image:"images/khasta-kachori.jpg",
        name:"Khasta kachori",
        category:"breakfast",
        price:"₹15",
        description:"a deep fried pastry,filled with savory stuffing,Indian cuisine and moong dal ", 
    },
    {
        id:2,
        image:"images/aloo-paratha.jpg",
        name:"Aloo Paratha",
        category:"breakfast",
        price:"₹20",
        description:"Indian breakfast of unleavened whole wheat flatbread stuffed with a spiced potato stuffing", 
    },
    {
        id:3,
        image:"images/samosa.jpg",
        name:"Samosa",
        category:"breakfast",
        price:"₹15",
        description:"a small triangular pastry case containing spiced vegetables and served fried.", 
    },
    {
        id:4,
        image:"images/chana-masala.jpg",
        name:"Chana Masala",
        category:"lunch",
        price:"₹80",
        description:"The main ingredient is a variety of chickpea called chana or kala chana", 
    },
    {
        id:5,
        image:"images/paneer-butter-masala.jpg",
        name:"Paneer Butter Masala",
        category:"lunch",
        price:"₹130",
        description:" a rich & creamy curry made with paneer, spices, onions, tomatoes, cashews and butter", 
    },
    {
        id:6,
        image:"images/masala-sandwich.jpg",
        name:"Masala Sandwich",
        category:"evening",
        price:"₹40",
        description:"crispy toasted sandwiches spiced with coriander chutney & fine sev topping", 
    },
    {
        id:7,
        image:"images/masala-dosa.jpg",
        name:"Masala Dosa",
        category:"evening",
        price:"₹35",
        description:"made from rice, lentils, potato, fenugreek, ghee and curry leaves, and served with chutneys & sambar.", 
    },
    {
        id:8,
        image:"images/gulab-jamun.jpg",
        name:"Gulab Jamun",
        category:"dinner",
        price:"₹20",
        description:"an Indian dessert of fried dough balls that are soaked in a sweet, sticky sugar syrup.", 
    },

    {
        id:9,
        image:"images/rice-kheer.jpg",
        name:"Rice Kheer",
        category:"lunch",
        price:"₹30",
        description:"a chilled South Asian dessert made from slow-cooked rice, milk, and sugar, much like a rice pudding.", 
    },
    {
        id:10,
         image:"images/chocolate-cake.jpg",
        name:"Chocolate Cake",
        category:"dinner",
        price:"₹400",
        description:"A cake flavored with melted chocolate, cocoa powder, or both.",
    },

    {
        id:11,
        image:"images/chocolate-cashew-bar.jpg",
        name:"Chocolate Cashew Bars",
        category:"evening",
        price:"₹40",
        description:" a sweet, gooey, tasty bar packed with plenty of chocolate and nuts.", 
    },

    {
        id:12,
        image:"images/chocolate-chip-cookies.jpg",
        name:"Chocolate Chip Cookies",
        category:"evening",
        price:"₹85",
        description:"made with butter and a combination of white and brown sugars which produces a rich and chewy cookie", 
    },

    {
        id:13,
        image:"images/Vanilla-Cake.jpg",
        name:"Vanilla Cake",
        category:"dinner",
        price:"₹350",
        description:" It has two moist and buttery cake layers that are filled and frosted with a delicious buttercream frosting", 
    },
    {
        id:14,
        image:"images/masala-corn.jpg",
        name:"Masala Corn",
        category:"dinner",
        price:"₹50",
        description:"boiled corns, butter, lemon juice and spices like chaat masala, garam masala, and chilli powder", 
    },
    {
        id:15,
        image:"images/fried-rice.jpeg",
        name:"fried rice",
        category:"dinner",
        price:"₹65",
        description:"dish combines the nutty flavor of rice with the fresh taste of bell peppers, baby peas, and other vegetables.", 
    },



    {
        id:16,
        image:"images/dhokla.jpg",
        name:"Khaman Dhokla",
        category:"breakfast",
        price:"₹45",
        description:"a fermented batter originated from rice, ground urad dal, and likewise chickpea flour.", 
    },
    {
        id:17,
        image:"images/Tawa-Naan.jpg",
        name:"Tawa Naan",
        category:"dinner",
        price:"₹10",
        description:"Naan is a popular Indian flatbread made using refined flour", 
    },

    {
        id:18,
        image:"images/tawa-roti.jpg",
        name:"Tawa Roti",
        category:"lunch",
        price:"₹7",
        description:"a traditional and tasty north indian flatbread recipe made with wheat flour using tawa on a top gas stove", 
    },
    {
        id:19,
        image:"images/puri.jpg",
        name:"Puri",
        category:"lunch",
        price:"₹25",
        description:"a simple unleavened bread made from just whole wheat flour, salt, and water.", 
    },
    {
        id:20,
        image:"images/tandoori-roti.jpeg",
        name:"Tandoori Roti",
        category:"dinner",
        price:"₹8",
        description:"tasty north indian flatbread recipe made with wheat flour traditionally made in tandoor oven.", 
    },
    {
        id:21,
        image:"images/kaju-paneer.jpg",
        name:"Kaju Paneer",
        category:"dinner",
        price:"₹85",
        description:"a unique tasty north indian curry made with cashews and paneer cubes.", 
    },
    {
        id:22,
        image:"images/sev-tamatar.jpg",
        name:"Sev Tamatar",
        category:"dinner",
        price:"₹65",
        description:"made from sev cooked in a tangy tomato gravy", 
    },
    {
        id:23,
        image:"images/dal-fry.jpg",
        name:"Dal Fry",
        category:"dinner",
        price:"₹75",
        description:"a delicious lentil that is made with tur dal (pigeon pea lentils), onions, tomatoes and spices",           
    },

    {
        id:24,
        image:"images/motichoor-laddu.jpg",
        name:"Motichoor Laddu",
        category:"lunch",
        price:"₹140",
        description:"a popular Indian sweet, made with besan (gram flour).", 
    },
    {
        id:25,
        image:"images/moong-dal-halwa.jpg",
        name:"Moong dal halwa",
        category:"breakfast",
        price:"₹25",
        description:"a classic Indian sweet dish made with moong lentils, sugar, ghee and cardamom powder.", 
    },
    {
        id:26,
        image:"images/Poha.jpeg",
        name:"Poha",
        category:"breakfast",
        price:"₹15",
        description:"flattened rice that is steam cooked with onions, spices and herbs", 
    },
    {
        id:27,
        image:"images/pani-puri.jpeg",
        name:"Pani Puri",
        category:"evening",
        price:"₹20",
        description:" is Round, hollow puri, filled with spicy green water, date-tamarind chutney, potatoes flavored, mung beans, chickpeas and chaat masala", 
    },
    // {
    //     id:28,
    //     image:"images/.jpg",
    //     name:"",
    //     category:"",
    //     price:"₹",
    //     description:"", 
    // },
    // {
    //     id:29,
    //     image:"images/.jpg",
    //     name:"",
    //     category:"",
    //     price:"₹",
    //     description:"", 
    // },



];

export default Menu;